site_name: Notes by Rob Kenis
repo_url: https://github.com/RobKenis/rob-kenis-dot-dev
repo_name: RobKenis/rob-kenis-dot-dev

site_description: Notes about conferences and trainings by Rob Kenis.
site_url: https://robkenis.dev

plugins:
  - search
  - git-revision-date-localized
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - rss

exclude_docs: |
  homelab/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RobKenis
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/RobKenis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/robkenis/
